### ISSUE TITLE
Fraud prevention trusted server

### ISSUE THREAD

**Issue by p-j-l** [antifraudcg/meetings#2]
Hey, we (Google Chrome, Human Security, Google Anti-Fraud) just posted a proposal here that we'd like to discuss at the 18th Feb meeting if there's time.  15 minutes should be enough time.

https://github.com/antifraudcg/proposals/issues/3

**Comment by dvorak42** [comment]
Added to the agenda. Please try to get the slides to the chairs by Thursday morning so we can add it to the agenda and folks can review.
