### ISSUE TITLE
Talk about UA Reduction and UA-CH

### ISSUE THREAD

**Issue by miketaylr** [antifraudcg/meetings#3]
If it's interesting to the group, I'd be happy to discuss Chrome's plans for User-Agent Reduction and User-Agent Client Hints.

**Comment by dvorak42** [comment]
Scheduled for the April 18th meeting.

**Comment by dvorak42** [comment]
*March 18th

**Comment by miketaylr** [comment]
Here are my slides: https://docs.google.com/presentation/d/1tec2bCpGHGM4FkX4y4GFlBwCa9dWs1ukGot-xkHRX-A/edit#slide=id.g10c56b38801_0_1933

**Comment by jwrosewell** [comment]
@miketaylr Can you confirm that the UA Reduction changes have been approved by the CMA under the commitments Google agreed with them in February 2022? I posted the same message on the [blink group](https://groups.google.com/a/chromium.org/g/blink-dev/c/-2JIRNMWJ7s/m/nkjrE7yYDgAJ) but I'm yet to receive a response.
