### ISSUE TITLE
Discussion Topic Proposal - Device Integrity Attestation + complementary capabilities

### ISSUE THREAD

**Issue by philippp** [antifraudcg/meetings#5]
The Privacy Sandbox Anti-Fraud team would like to share our reasoning behind "Device Integrity Attestation through the Browser" (https://github.com/antifraudcg/proposals/issues/8), and discuss whether it may be a helpful component in the prevention of fraud and abuse. We will quickly review what this could look like on iOS and Android, open challenges for other platforms, and survey what other capabilities would be useful to investigate and potentially provide (Michael Ficarra mentioned "uniqueness," for example).

**Comment by dvorak42** [comment]
Scheduled for this week's meeting.
